spring:
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.117.163.255:3306/xmzdb
    username: root
    password: xmzpassword
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000         # 等待连接超时时间（毫秒）
      max-lifetime: 180000              # 连接最大生命周期（毫秒），建议小于数据库 idle 超时时间（如 3分钟）
      idle-timeout: 60000               # 空闲连接超时时间
      validation-timeout: 5000          # 连接校验的超时时间
      connection-test-query: SELECT 1  # 心跳 SQL，确保拿出的连接是可用的
server:
  port: 8181
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# 微信公众号对接
weixin:
  config:
    originalid: gh_5c4a22337280
    token: onepiecexmz
    app-id: wxf4a59accd4e400ef
    app-secret: 0138ff87eb1fe818b8355bbd4ce58b36
    template_id: LTKimOk6EUGsP6R-VnWN03X5fAgOg_QDkHGttTPxjiM
  qrcode:
    api:
      url: https://mp.weixin.qq.com/cgi-bin/showqrcode